# Generated by Django 2.1.5 on 2019-01-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190131_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='salary',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
