# Generated by Django 2.1.7 on 2019-02-14 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_person_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='photo',
            new_name='Foto',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='Idade',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='Primeiro_Nome',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='salary',
            new_name='Salário',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='Último_Nome',
        ),
    ]
