# Generated by Django 2.1.7 on 2019-02-14 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20190214_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Foto',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Idade',
            new_name='idade',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Primeiro_Nome',
            new_name='primeiro_nome',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Salário',
            new_name='salario',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Último_Nome',
            new_name='ultimo_nome',
        ),
    ]
